package com.principal;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatAtomOneLightIJTheme;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        InitContent();
    }

    private void InitContent() {
    }

    private void ShowJpanel(JPanel pl) {
        pl.setSize(735, 492);
        pl.setLocation(0, 0);

        content.removeAll();
        content.add(pl, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        salirbtn = new javax.swing.JButton();
        ctrlpanelbtn = new javax.swing.JButton();
        asistenciasbtn = new javax.swing.JButton();
        empleadosbtn = new javax.swing.JButton();
        nominabtn = new javax.swing.JButton();
        opcionesbtn = new javax.swing.JButton();
        empleadosbtn1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        content = new javax.swing.JPanel();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1245, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 470));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 825, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(20, 48, 66));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(54, 70, 80));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconos/Search.png"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 30, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/account_circle_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel3.setText("USER");
        jLabel3.setIconTextGap(6);
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 40));

        jTextField1.setBackground(new java.awt.Color(54, 70, 80));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 20));

        jLabel2.setBackground(new java.awt.Color(0, 153, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN PRODUZCA");
        jLabel2.setOpaque(true);
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        salirbtn.setBackground(new java.awt.Color(20, 48, 66));
        salirbtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        salirbtn.setForeground(new java.awt.Color(204, 204, 204));
        salirbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/door_open_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        salirbtn.setText("Salir");
        salirbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        salirbtn.setBorderPainted(false);
        salirbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salirbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salirbtn.setIconTextGap(6);
        salirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirbtnActionPerformed(evt);
            }
        });
        jPanel5.add(salirbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 160, 40));

        ctrlpanelbtn.setBackground(new java.awt.Color(20, 48, 66));
        ctrlpanelbtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ctrlpanelbtn.setForeground(new java.awt.Color(204, 204, 204));
        ctrlpanelbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dock_to_right_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        ctrlpanelbtn.setText("Panel de Control");
        ctrlpanelbtn.setBorder(null);
        ctrlpanelbtn.setBorderPainted(false);
        ctrlpanelbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ctrlpanelbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ctrlpanelbtn.setIconTextGap(6);
        ctrlpanelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlpanelbtnActionPerformed(evt);
            }
        });
        jPanel5.add(ctrlpanelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, 160, 40));

        asistenciasbtn.setBackground(new java.awt.Color(20, 48, 66));
        asistenciasbtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        asistenciasbtn.setForeground(new java.awt.Color(204, 204, 204));
        asistenciasbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/event_available_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        asistenciasbtn.setText("Asistencias");
        asistenciasbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        asistenciasbtn.setBorderPainted(false);
        asistenciasbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asistenciasbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        asistenciasbtn.setIconTextGap(6);
        asistenciasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asistenciasbtnActionPerformed(evt);
            }
        });
        jPanel5.add(asistenciasbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 160, 40));

        empleadosbtn.setBackground(new java.awt.Color(20, 48, 66));
        empleadosbtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        empleadosbtn.setForeground(new java.awt.Color(204, 204, 204));
        empleadosbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/person_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        empleadosbtn.setText("Lista de Empleados\n");
        empleadosbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        empleadosbtn.setBorderPainted(false);
        empleadosbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empleadosbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        empleadosbtn.setIconTextGap(6);
        empleadosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosbtnActionPerformed(evt);
            }
        });
        jPanel5.add(empleadosbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 160, 40));

        nominabtn.setBackground(new java.awt.Color(20, 48, 66));
        nominabtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nominabtn.setForeground(new java.awt.Color(204, 204, 204));
        nominabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/groups_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        nominabtn.setText("Nomina");
        nominabtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        nominabtn.setBorderPainted(false);
        nominabtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nominabtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nominabtn.setIconTextGap(6);
        nominabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nominabtnActionPerformed(evt);
            }
        });
        jPanel5.add(nominabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 160, 40));

        opcionesbtn.setBackground(new java.awt.Color(20, 48, 66));
        opcionesbtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        opcionesbtn.setForeground(new java.awt.Color(204, 204, 204));
        opcionesbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/settings_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        opcionesbtn.setText("Cargos");
        opcionesbtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        opcionesbtn.setBorderPainted(false);
        opcionesbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        opcionesbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        opcionesbtn.setIconTextGap(6);
        opcionesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionesbtnActionPerformed(evt);
            }
        });
        jPanel5.add(opcionesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 160, 40));

        empleadosbtn1.setBackground(new java.awt.Color(20, 48, 66));
        empleadosbtn1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        empleadosbtn1.setForeground(new java.awt.Color(204, 204, 204));
        empleadosbtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/person_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        empleadosbtn1.setText("Registro");
        empleadosbtn1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        empleadosbtn1.setBorderPainted(false);
        empleadosbtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empleadosbtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        empleadosbtn1.setIconTextGap(6);
        empleadosbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadosbtn1ActionPerformed(evt);
            }
        });
        jPanel5.add(empleadosbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 160, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 520));

        jPanel6.setBackground(new java.awt.Color(0, 153, 204));

        jLabel4.setBackground(new java.awt.Color(0, 153, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Iconos/User Male.png"))); // NOI18N
        jLabel4.setText("Prueba");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 560, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 730, 30));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 729, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 730, 520));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void salirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirbtnActionPerformed
        // TODO add your handling code here:
        
        
        int op = JOptionPane.showConfirmDialog(null, "Seguro que desea salir?", "CERRAR SESION", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if (op==0) {
            JOptionPane.showMessageDialog(null, "Hasta luego :D", "Sesion Cerrada", JOptionPane.INFORMATION_MESSAGE);
            
            login loginframe = new login();
            loginframe.setVisible(true);
            loginframe.pack();
            loginframe.setLocationRelativeTo(null);
            this.dispose();
            
        }
    }//GEN-LAST:event_salirbtnActionPerformed

    private void opcionesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionesbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionesbtnActionPerformed

    private void ctrlpanelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlpanelbtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ctrlpanelbtnActionPerformed

    private void empleadosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosbtnActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_empleadosbtnActionPerformed

    private void nominabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nominabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nominabtnActionPerformed

    private void asistenciasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asistenciasbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asistenciasbtnActionPerformed

    private void empleadosbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadosbtn1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_empleadosbtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            FlatAtomOneLightIJTheme.setup();

        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asistenciasbtn;
    private javax.swing.JPanel content;
    private javax.swing.JButton ctrlpanelbtn;
    private javax.swing.JButton empleadosbtn;
    private javax.swing.JButton empleadosbtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton nominabtn;
    private javax.swing.JButton opcionesbtn;
    private javax.swing.JButton salirbtn;
    // End of variables declaration//GEN-END:variables
}
