/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

import clases.Conexion;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author VictorY
 */
public class panelhistoria extends javax.swing.JPanel {

    /**
     * Creates new form prueba
     */
    public panelhistoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldci = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areapaciente = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        searchbtn.setText("Buscar");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        areapaciente.setColumns(20);
        areapaciente.setRows(5);
        jScrollPane2.setViewportView(areapaciente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldci, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchbtn)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        try {
            String cii = fieldci.getText().trim();
            if (cii.isBlank()) {
                JOptionPane.showMessageDialog(null, "Ingrese la cedula del paciente", "ERROR", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method if input is blank

             String cio = fieldci.getText().trim();
             if (cio.isBlank()) {
                JOptionPane.showMessageDialog(null, "Ingrese la cedula del paciente", "ERROR", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method if input is blank
            }
             
            
             

            Conexion cn = new Conexion();
            Connection conexion = cn.conectar();

            // Use a prepared statement to prevent SQL injection
            PreparedStatement ps = conexion.prepareStatement("SELECT * FROM pacientes WHERE CI = ?");
            ps.setString(1, cii);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                areapaciente.setText("Datos personales::\nCI: "+rs.getString("CI")+"\nNombre: "+rs.getString("nombre_paciente")+"\nApellido: "+rs.getString("apellido_paciente")+"\nFecha de nacimiento: "+rs.getDate("fecha_nacimiento")+"\nGénero: "+rs.getString("genero_paciente")+"\nDirección: "+rs.getString("direccion_paciente")+"\nTeléfono: "+rs.getString("tel_paciente"));
                        
                
            } else {
                JOptionPane.showMessageDialog(null, "No existe el paciente", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
           
        } 
       
            
          Conexion ct = new Conexion();
            Connection conexion = ct.conectar();
            
          PreparedStatement ps = conexion.prepareStatement("SELECT * FROM consultasmedicas WHERE CI = ?");
            ps.setString(1, cio);

            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                areapaciente.setText("Detalles de la consulta:\nID Consulta: "+rs.getString("id_consulta")+"\nCédula del Paciente: "+rs.getString("CI")+"\nID del Médico: "+rs.getString("id_medico")+"\nFecha de la consulta: "+rs.getDate("fecha_consulta")+"\nDiágnostico: "+rs.getString("diagnostico")+"\nReceta: "+rs.getString("receta"));
                        
            } else {
                JOptionPane.showMessageDialog(null, "No existe el paciente", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger("panelhistoria").log(Level.SEVERE, "Error buscando paciente", ex);
        }

    }//GEN-LAST:event_searchbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areapaciente;
    private javax.swing.JTextField fieldci;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton searchbtn;
    // End of variables declaration//GEN-END:variables
}
